In [3]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [4]:
np.random.rand(3,3,3)

array([[[0.55821202, 0.70387686, 0.81515452],
        [0.90870521, 0.95600067, 0.83116658],
        [0.85394292, 0.10162119, 0.99748982]],

       [[0.33772276, 0.54524258, 0.39414454],
        [0.85323413, 0.61171545, 0.12321565],
        [0.65034656, 0.98158309, 0.63273326]],

       [[0.06122499, 0.16323264, 0.15076443],
        [0.85856705, 0.37501151, 0.36155411],
        [0.88360047, 0.05743057, 0.64864738]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
np.diag(1+np.arange(4),k=-1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
A= np.zeros((8,8),dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [9]:
A= np.random.random((5,5))
A = (A - np.mean (A)) / (np.std (A))
print(A)

[[-0.97205905 -0.79383286 -0.18715428  0.58449856  1.38079831]
 [-0.33939746  0.9274707  -0.69295055  0.99111757 -0.94813102]
 [-0.35016555  0.57148003 -1.57713644  1.35649191 -1.11739538]
 [-1.49085869 -1.30094738  0.48037986  0.49535482  1.18738889]
 [-0.2320113   1.4593025   0.80202145 -1.36700946  1.13274481]]


# 5.  How to find common values between two arrays?

In [11]:
A1 = np.random.randint(0,10,10)
A2 = np.random.randint(0,10,10)
print(np.intersect1d(A1,A2))

[4 5 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [12]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-08-01
2020-08-02
2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [15]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.69827062 0.5760738  0.6073829  0.84538755 0.1269173  0.21430403
 0.76735442 0.61474913 0.46102945 0.        ]


# 9. How to print all the values of an array?

In [16]:
np.set_printoptions(threshold=float("inf"))
A= np.zeros((16,16))
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [17]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y1 = X - X.mean(axis=1).reshape(-1, 1)
print(Y)
print(Y1)

[[ 0.47882672 -0.42283861 -0.29132432  0.41674149  0.32243292  0.0513938
   0.0668838  -0.06946224 -0.42670019 -0.12595336]
 [ 0.10685793 -0.43277969 -0.47523541  0.41813954  0.49003562 -0.29607354
  -0.13768444  0.40646587  0.18736209 -0.26708797]
 [-0.27544236  0.36150047 -0.03799499 -0.17630064  0.26103441  0.03939266
  -0.28344122 -0.13027505  0.14234806  0.09917866]
 [-0.35665756 -0.3438361  -0.23221552  0.41657401  0.02170542  0.40583736
   0.37884518  0.14285255 -0.16478336 -0.26832197]
 [ 0.30425697  0.11336618  0.18708783 -0.34311208  0.25540309 -0.01346388
  -0.55137597  0.38973582 -0.26674062 -0.07515733]]
[[ 0.47882672 -0.42283861 -0.29132432  0.41674149  0.32243292  0.0513938
   0.0668838  -0.06946224 -0.42670019 -0.12595336]
 [ 0.10685793 -0.43277969 -0.47523541  0.41813954  0.49003562 -0.29607354
  -0.13768444  0.40646587  0.18736209 -0.26708797]
 [-0.27544236  0.36150047 -0.03799499 -0.17630064  0.26103441  0.03939266
  -0.28344122 -0.13027505  0.14234806  0.09917866]
 

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [19]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 3. 3. 6. 2. 1. 2. 2. 4. 3.]


In [20]:
np.add.at(Z, I, 1)
print(Z)

[ 7.  5.  5. 11.  3.  1.  3.  3.  7.  5.]


# 12.How to get the diagonal of a dot product?

In [25]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
prod1=np.diag(np.dot(A, B))
prod2=np.sum(A * B.T, axis=1)
print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.29241553 0.99597975 0.15158285 0.00580775 0.69333814]
 [0.71690309 0.36246284 0.707732   0.74675011 0.24134656]
 [0.28636687 0.22541556 0.32945244 0.03049076 0.22273354]
 [0.92777361 0.29744739 0.43392697 0.44083764 0.70971654]
 [0.56102595 0.26374534 0.41334102 0.29421957 0.48754783]]
[[0.72632475 0.59368848 0.39494256 0.97442199 0.03286479]
 [0.29145717 0.76993976 0.93514906 0.37271605 0.69146878]
 [0.91657361 0.79258397 0.87655828 0.37733776 0.94143198]
 [0.58496825 0.62360827 0.23133811 0.0828263  0.70769071]
 [0.43310902 0.18205718 0.05540791 0.43745953 0.19160074]]
diagonal of a dot product method 1 is.... [0.94529927 1.77524711 0.63207475 1.52562867 0.89157311]
diagonal of a dot product method 2 is.... [0.94529927 1.77524711 0.63207475 1.52562867 0.89157311]


# 13.How to find the most frequent value in an array?

In [22]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[0 6 4 3 7 6 3 6 0 6 1 3 9 0 2 3 8 2 7 1 1 4 8 6 6 0 8 6 4 0 1 8 5 8 4 8 2
 6 2 6 6 6 4 7 1 2 0 2 5 0]
6


# 14.How to get the n largest values of an array

In [26]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [24]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
